### ISSUE TITLE
Missing data/nyc_taxi.pkl

### ISSUE THREAD

**Issue by cedricyau** [jonmmease/plotly_ipywidget_notebooks#1]
Demo and the widget wrapper is awesome!  Would love to be able to run this myself.  Can you add 'data/nyc_taxi.pkl' to the repo?

![image](https://user-images.githubusercontent.com/6124063/42655968-b7c5217e-85eb-11e8-9e4d-f2a8312a85c5.png)

Thanks,
Cedric

**Comment by jonmmease** [comment]
I just updated the notebook with some logic to download the file if it's not found. Thanks!
